# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [ ]:
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False

In [266]:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

print("Result is ",ElementCheck(numbers_x))
print("Result is ",ElementCheck(numbers_y))

def ElementCheck(List):
    return List[0]==List[-1]
    

Result is  True
Result is  False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [33]:
import numpy as np

L1 = [0,1,2,3,4]
L2 = [1,2,3,4,5]
Array1 = np.array(L1)
Array2 = np.array(L2)

print("First Array is: ",Array1)
print("Second Array is: ",Array2)
print()
print("After Addition: ",Array1 + Array2)
print("After Element-wise product is: ",Array1*Array2)


First Array is:  [0 1 2 3 4]
Second Array is:  [1 2 3 4 5]

After Addition:  [1 3 5 7 9]
After Element-wise product is:  [ 0  2  6 12 20]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [52]:
#code here

L1 = [1,2,3,4,5,6,7,8,9,10,11,12]
Array = np.array(L1)
print("1D Numpy Array is: ",Array)
Reshaped = Array.reshape(3,4)
print("Reshaped 2D Array is: ")
print(Reshaped)
print()

Reshaped2 = Reshaped

Array1 = np.concatenate((Reshaped,Reshaped2),axis=0)
print("Vertically Concatenated Arrays are: ")
print(Array1)
print()

Array2 = np.concatenate((Reshaped,Reshaped2),axis=1)
print("Horizontally Concatenated Arrays are: ")
print(Array2)
print()



1D Numpy Array is:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 2D Array is: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Vertically Concatenated Arrays are: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Horizontally Concatenated Arrays are: 
[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]



# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [62]:
#Code here

count = 1
shopping_cart = []
items = ['Phone','Laptop','Ipad','PC','Keyboard','Mouse','Wires','Printer','Speaker','Microphone']

print("Welcome to Online Tech Store!")
print("The Following Items are available in Store Currently!")
for x in items:
    print(count,x)
    count = count + 1
print()
print("Please Enter 'A' to shop")
choice = input()
print()
while(choice!='q'):
    print("Please Add Corresponding No. of Item you want to Add in Cart")
    item = int(input())
    shopping_cart.append(items[item-1])
    print("Your Current Cart is: ",shopping_cart)
    print()
    print("Please Enter 'A' to continue, or enter 'q' to stop ")
    choice = input()
    print()

print()
print()
print("Items you purchased are: ",shopping_cart)
print("Thank You For Shopping at our Store!")


Welcome to Online Tech Store!
The Following Items are available in Store Currently!
1 Phone
2 Laptop
3 Ipad
4 PC
5 Keyboard
6 Mouse
7 Wires
8 Printer
9 Speaker
10 Microphone

Please Enter 'A' to shop


 A



Please Add Corresponding No. of Item you want to Add in Cart


 2


Your Current Cart is:  ['Laptop']

Please Enter 'A' to continue, or enter 'q' to stop 


 A



Please Add Corresponding No. of Item you want to Add in Cart


 7


Your Current Cart is:  ['Laptop', 'Wires']

Please Enter 'A' to continue, or enter 'q' to stop 


 q





Items you purchased are:  ['Laptop', 'Wires']
Thank You For Shopping at our Store!


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [270]:
#code here
import nltk
from nltk.tokenize import sent_tokenize

def classify_emails(List):
    important = []
    promotion = []
    spam = []
    for x in List:
        sentences = sent_tokenize(x)
        imp_count = sum(sent.count(word) for sent in sentences for word in imp)
        prom_count = sum(sent.count(word) for sent in sentences for word in prom)
        spam_count = sum(sent.count(word) for sent in sentences for word in spamm)
        if imp_count>prom_count and imp_count>spam_count:
            important.append(x)
        elif (prom_count>imp_count and prom_count>spam_count):
            promotion.append(x)
        elif spam_count>imp_count and spam_count>prom_count:
            spam.append(x)
    return important,promotion,spam


imp = ['important','main','principal','key','urgent']
prom = ['promotion','promotional','buy','sale']
spamm = ['spam','spamm','repeated']

Email = ['This is a very important email. Please respond to it as soon as possible','This is a spam email','This is a promotional Email','This is a spam promotion spam email','This is not a promotion or a spam email but a very important and urgent email']
impp,promo,spam = classify_emails(Email)
print('Important Emails are: ')
print(impp)
print()
print('Promotional Emails are: ')
print(promo)
print()
print('Spam Emails are: ')
print(spam)



Important Emails are: 
['This is a very important email. Please respond to it as soon as possible', 'This is not a promotion or a spam email but a very important and urgent email']

Promotional Emails are: 
['This is a promotional Email']

Spam Emails are: 
['This is a spam email', 'This is a spam promotion spam email']


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [206]:
#code here

english_to_spanish = {
    "hello": "hola",
    "goodbye": "adiós",
    "thank you": "gracias",
    "please": "por favor",
    "yes": "sí",
    "no": "no",
    "dog": "perro",
    "cat": "gato",
    "house": "casa",
    "friend": "amigo",
}

choice = 'A'

while(choice!='Q'):
    print('Please Enter The English Word: ')
    word = input()
    if word in english_to_spanish:
        print(word,'in Spanish is: ',english_to_spanish[word])
    else:
        print('The Word ',word,'Does not Exist in the Dictionary')
    print()
    print('Please Enter A to Continue, or Enter Q to Quit')
    choice = input()
    print()
        
    




Please Enter The English Word: 


 home


The Word  home Does not Exist in the Dictionary

Please Enter A to Continue, or Enter Q to Quit


 A



Please Enter The English Word: 


 hello


hello in Spanish is:  hola

Please Enter A to Continue, or Enter Q to Quit


 Q


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [251]:
import pandas as pd

url = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
data = pd.read_csv(url)
data


Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [252]:
print('Total of Global Sales is:',data['Global_Sales'].sum())


Total of Global Sales is: 8920.44


In [253]:
maxx = data[(data['Global_Sales']==max(data['Global_Sales']))]
maxx

Rank        Name Platform    Year   Genre Publisher  NA_Sales  EU_Sales  \
0     1  Wii Sports      Wii  2006.0  Sports  Nintendo     41.49     29.02   

   JP_Sales  Other_Sales  Global_Sales  
0      3.77         8.46         82.74

In [258]:
print('Average of NA Sales:',data['NA_Sales'].mean())
print('Average of EU Sales:',data['EU_Sales'].mean())
print('Average of JP Sales:',data['JP_Sales'].mean())
print('Average of Other Sales:',data['Other_Sales'].mean())

Average of NA Sales: 0.26466742981082064
Average of EU Sales: 0.14665200626581515
Average of JP Sales: 0.077781660441017
Average of Other Sales: 0.0480630196409206


In [257]:
top_genres = data.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print('Top 5 Genre According to Global Sales are: ')
print(top_genres)

Top 5 Genre According to Global Sales are: 
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [259]:
region = data.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
region

NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36

In [260]:
popular = sales_by_genre_region['NA_Sales'].idxmax()
print('Most Popular Genre in NA is: ',popular)

Most Popular Genre in NA is:  Action


In [261]:
data.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [263]:
top_platforms = data.groupby('Platform')['Global_Sales'].sum().nlargest(3)
top_platforms

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

In [250]:
market_share = (data.groupby('Genre')['Global_Sales'].sum() / data['Global_Sales'].sum()) * 100
market_share

Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64

In [249]:
correlation_coefficient = data['NA_Sales'].corr(data['EU_Sales'])
correlation_coefficient

0.767726748370264